[[language]]
name = "fennel"
scope = "source.fnl"
injection-regex = "(fennel|fnl)"
file-types = ["fnl"]
shebangs = ["fennel"]
comment-token = ";"
formatter = { command = "fnlfmt", args = ["-"] }
indent = { tab-width = 2, unit = "  " }
roots = []
grammar = "scheme"
