default_flags = "g"

# not working, find alternative or wait for upstream
[[verbs]]
key = "ctrl-="
internal = ":stage"

# not working, find alternative or wait for upstream
[[verbs]]
key = "ctrl--"
internal = ":unstage"

[[verbs]]
key = "ctrl-d"
internal = ":focus ~/dev"
